---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"

inputs:
  - name: git-repo

outputs:
  - name: artifact

run:
  path: git-repo/ci/scripts/build.sh
