apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
spec:
  type: {{.Values.service.type}}        # Added .service.
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}    # Added .service.
      targetPort: {{.Values.service.targetPort}} # Added .service.
